version: '3.8'

services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: atlas_ipfs
    ports:
      - "4001:4001" # Swarm TCP
      - "4001:4001/udp" # Swarm UDP
      - "127.0.0.1:5001:5001" # API (Localhost only for security)
      - "127.0.0.1:8080:8080" # Gateway
    volumes:
      - ./data/ipfs_staging:/export
      - ./data/ipfs_data:/data/ipfs
    environment:
      - IPFS_PROFILE=server
    # command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]

  # Future: atlas_backend, atlas_frontend
